import type { Metadata } from "next";
import { AlertTriangle, ArrowDownRight, ArrowUpRight, DatabaseZap, Gauge, Info, RefreshCw, Scale, WalletCards } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { KpiCard, PageHeading, Pagination } from "@/components/page-parts";
import { ledgerEntries, poolBuckets } from "@/lib/demo-data";

export const metadata:Metadata={title:"VND 资金池"};
export default function PoolPage(){
 return <>
  <PageHeading title="VND 资金池" subtitle="来源桶、同比例消耗与成本基础的 Shadow Mode 总览" actions={<><Button><RefreshCw size={13}/>刷新快照</Button><Button variant="default"><Scale size={14}/>录入期初余额</Button></>}/>
  <div className="kpi-grid"><KpiCard label="VND 总可用余额" value="10,946,821,500 ₫" note={<><span className="trend-up">+2.3%</span><span>较昨日 UTC 00:00</span></>} icon={WalletCards}/><KpiCard label="USDT 等值" value="412,523.91" note={<span>参考汇率 26,536.20 · 09:00 UTC</span>} icon={Gauge} color="#0f9f78"/><KpiCard label="今日 Payin 流入" value="1,284,500,000 ₫" note={<><ArrowUpRight size={11} className="trend-up"/><span>48 笔成功订单</span></>} icon={ArrowUpRight} color="#6f4bb7"/><KpiCard label="今日 Payout 流出" value="860,000,000 ₫" note={<><ArrowDownRight size={11} className="trend-down"/><span>31 笔成功订单</span></>} icon={ArrowDownRight} color="#dc8b16"/></div>
  <div className="grid-2">
   <Card><CardHeader><div><h2 className="panel-title">资金来源构成</h2><div className="panel-subtitle">Payout 按发生前可用余额占比进行整数分摊</div></div><Badge variant="green">余额充足</Badge></CardHeader><CardContent><div className="pool-bar" aria-label="资金来源比例">{poolBuckets.map(bucket=><span key={bucket.source} style={{width:bucket.pct,background:bucket.color}}/>)}</div><div className="bucket-list">{poolBuckets.map(bucket=><div className="bucket-card" key={bucket.source}><div className="bucket-label"><span className="color-dot" style={{background:bucket.color}}/>{bucket.label}<Badge variant={bucket.cost==="KNOWN"?"green":bucket.cost==="MISSING"?"red":"amber"}>{bucket.cost}</Badge></div><div className="bucket-value">{bucket.value} ₫</div><div className="bucket-meta"><span>{bucket.source}</span><strong>{bucket.pct}</strong></div></div>)}</div></CardContent></Card>
   <Card><CardHeader><div><h2 className="panel-title">流动性预警</h2><div className="panel-subtitle">低池阈值 50,000 USDT</div></div><Badge variant="green">正常</Badge></CardHeader><CardContent><div style={{display:"flex",alignItems:"center",gap:14,marginBottom:18}}><div style={{width:56,height:56,borderRadius:"50%",display:"grid",placeItems:"center",background:"conic-gradient(#0f9f78 0 82%,#e8edf2 82%)",position:"relative"}}><span style={{width:43,height:43,borderRadius:"50%",background:"white",display:"grid",placeItems:"center",fontSize:10,fontWeight:700}}>8.25×</span></div><div><div className="metric-label">当前余额 / 预警阈值</div><div style={{fontSize:17,fontWeight:720,marginTop:5}}>412,523.91 USDT</div></div></div><div className="metric-list"><div className="metric-row"><span className="metric-label">参考汇率</span><span className="metric-value">26,536.20000000</span></div><div className="metric-row"><span className="metric-label">汇率来源</span><span className="metric-value">Manual Treasury Ref</span></div><div className="metric-row"><span className="metric-label">汇率时间</span><span className="metric-value">2026-07-21 09:00 UTC</span></div><div className="metric-row"><span className="metric-label">数据可信度</span><Badge variant="green">HIGH</Badge></div></div></CardContent></Card>
  </div>
  <div className="alert alert-warning" style={{marginBottom:16}}><AlertTriangle size={16}/><div><strong>2 个资金桶缺少可靠成本基础</strong>OPENING 与部分 PAYIN 桶的 funding_cost_usdt 未确认，系统保留 MISSING / ESTIMATED；内部划转费为 0 不代表资金经济价值为 0。</div></div>
  <Card><CardHeader><div><h2 className="panel-title">最近资金池流水</h2><div className="panel-subtitle">余额变化按事件时间排序 · 所有 VND 以整数入账</div></div><Button><DatabaseZap size={13}/>查看完整账本</Button></CardHeader><div className="table-wrap"><table><thead><tr><th>事件时间 (UTC)</th><th>事件类型</th><th>来源</th><th>业务参考</th><th style={{textAlign:"right"}}>变动金额 (VND)</th><th style={{textAlign:"right"}}>变动后余额 (VND)</th><th>可信度</th></tr></thead><tbody>{ledgerEntries.map((entry,index)=><tr key={`${entry.ref}-${index}`}><td>{entry.time}</td><td><Badge variant={entry.type.includes("INFLOW")?"green":"blue"}>{entry.type}</Badge></td><td><Badge variant={entry.source==="TOPUP"?"violet":entry.source==="MIXED"?"gray":"blue"}>{entry.source}</Badge></td><td className="mono">{entry.ref}</td><td className="money" style={{color:entry.amount.startsWith("+")?"#087f5b":"#b82f3a"}}>{entry.amount}</td><td className="money">{entry.balance}</td><td><Badge variant={entry.confidence==="高"?"green":"amber"}>{entry.confidence}</Badge></td></tr>)}</tbody></table></div><Pagination total={186}/></Card>
  <div className="alert alert-info" style={{marginTop:16}}><Info size={15}/><div><strong>事件时间规则</strong>Payin 优先取 completed_at；缺失时退回 created_at 并降低可信度。只有最终成功的 Payout 减少余额，失败、超时和取消订单不会生成流出。</div></div>
 </>;
}
