import type { Metadata } from "next";
import { AlertCircle, CalendarClock, CheckCircle2, CircleHelp, Copy, Download, Filter, RefreshCw, Search, ShieldAlert, WalletCards } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { PageHeading, Pagination } from "@/components/page-parts";
export const metadata:Metadata={title:"数据质量与审计"};
const issues=[
 {icon:ShieldAlert,title:"Payin 手续费校验差异",description:"导入手续费与订单金额 × 0.8% 超出 1 VND 容差",count:"7",unit:"笔订单",severity:"red" as const},
 {icon:AlertCircle,title:"AP 关系校验差异",description:"AP_IMPORTED 与 AS / AR − 1 不一致",count:"3",unit:"笔订单",severity:"red" as const},
 {icon:CircleHelp,title:"AQ 组合关系待确认",description:"AQ 已包含在 AR→AS 中，不额外参与利润计算",count:"864",unit:"笔订单",severity:"amber" as const},
 {icon:WalletCards,title:"缺少资金成本汇率",description:"OPENING / PAYIN 桶未确认 USDT 成本基础",count:"2",unit:"个资金桶",severity:"amber" as const},
 {icon:CalendarClock,title:"补U仅有日期精度",description:"不得用于分钟级回测或伪造执行时刻",count:"3",unit:"个批次",severity:"amber" as const},
 {icon:Copy,title:"重复订单或文件",description:"已由文件哈希与 raw_row_hash 阻止写入",count:"22",unit:"条记录",severity:"blue" as const},
];
const validations=[
 {id:"PI-835779",type:"PAYIN_FEE",imported:"7,998 ₫",calculated:"8,000 ₫",diff:"−2 ₫",status:"MISMATCH",batch:"IMP-20260721-004"},
 {id:"PI-835812",type:"PAYIN_FEE",imported:"2,499 ₫",calculated:"2,500 ₫",diff:"−1 ₫",status:"MATCH",batch:"IMP-20260721-004"},
 {id:"PO-291019",type:"AP_RELATION",imported:"0.02150000",calculated:"0.02148263",diff:"0.00001737",status:"MISMATCH",batch:"IMP-20260721-003"},
 {id:"PO-291022",type:"AQ_COMPOSITION",imported:"AQ 0.0042",calculated:"UNKNOWN",diff:"诊断专用",status:"REVIEW",batch:"IMP-20260721-003"},
];
export default function DataQualityPage(){return <>
 <PageHeading title="数据质量与审计" subtitle="跨导入、关系公式、资金成本与事件时间的集中验证" actions={<><Button><Download size={13}/>导出错误报告</Button><Button variant="default"><RefreshCw size={13}/>重新运行校验</Button></>}/>
 <div className="quality-grid"><div className="quality-card"><span className="quality-score" style={{color:"#087f5b",background:"#ecf9f4"}}>98.7</span><div><div className="quality-title">数据完整度</div><div className="quality-note">2,093 / 2,120 个必填字段完整</div></div></div><div className="quality-card"><span className="quality-score" style={{color:"#245cc0"}}>99.5</span><div><div className="quality-title">关系一致性</div><div className="quality-note">手续费与 AP 数学验证通过率</div></div></div><div className="quality-card"><span className="quality-score" style={{color:"#a96506",background:"#fff7e9"}}>中</span><div><div className="quality-title">当前可信度</div><div className="quality-note">受日期级时间与成本缺失影响</div></div></div></div>
 <div className="grid-2"><Card><CardHeader><div><h2 className="panel-title">待处理问题</h2><div className="panel-subtitle">按风险和业务影响聚合</div></div><Badge variant="red">12 项需处理</Badge></CardHeader><CardContent><div className="issue-list">{issues.map(issue=><div className="issue" key={issue.title}><span className="issue-icon" style={issue.severity==="red"?{background:"#fff0f1",color:"#b82f3a"}:issue.severity==="blue"?{background:"#eff5ff",color:"#205ab4"}:undefined}><issue.icon size={15}/></span><div><div className="issue-title">{issue.title}</div><div className="issue-description">{issue.description}</div></div><div className="issue-count">{issue.count}<small>{issue.unit}</small></div></div>)}</div></CardContent></Card>
 <div style={{display:"grid",gap:16,alignContent:"start"}}><Card><CardHeader><div><h2 className="panel-title">AQ 关系状态</h2><div className="panel-subtitle">正式计算边界</div></div><Badge variant="amber">UNKNOWN</Badge></CardHeader><CardContent><div className="alert alert-warning"><CircleHelp size={16}/><div><strong>关系公式待确认</strong>AQ 一定包含在 AR 变为 AS 的过程中，但与其他项的组合方式尚未确认。</div></div><div className="metric-list" style={{marginTop:16}}><div className="metric-row"><span className="metric-label">正式 AP</span><span className="metric-value">AS / AR − 1</span></div><div className="metric-row"><span className="metric-label">加法残差</span><Badge variant="gray">diagnostic_only</Badge></div><div className="metric-row"><span className="metric-label">乘法残差</span><Badge variant="gray">diagnostic_only</Badge></div><div className="metric-row"><span className="metric-label">AQ 额外计费</span><Badge variant="green">禁止</Badge></div></div></CardContent></Card><div className="alert alert-info"><CheckCircle2 size={16}/><div><strong>敏感数据检查通过</strong>本次批次未发现完整银行卡号或无业务必要的姓名字段进入数据库载荷。</div></div></div></div>
 <Card><CardHeader><div><h2 className="panel-title">校验明细</h2><div className="panel-subtitle">原始导入值始终保留，系统计算值与差异单独存储</div></div><Badge variant="blue">最近批次</Badge></CardHeader><div className="toolbar"><div className="search"><Search size={14}/><input placeholder="搜索订单号、批次…"/></div><select className="select"><option>全部校验类型</option><option>Payin 手续费</option><option>AP 关系</option><option>AQ 关系</option></select><select className="select"><option>全部状态</option><option>不一致</option><option>待复核</option><option>一致</option></select><span className="toolbar-spacer"/><Button><Filter size={13}/>更多筛选</Button></div><div className="table-wrap"><table><thead><tr><th>业务编号</th><th>校验类型</th><th>导入值</th><th>系统计算值</th><th>差异 / 说明</th><th>状态</th><th>导入批次</th></tr></thead><tbody>{validations.map(row=><tr key={row.id}><td className="mono">{row.id}</td><td><Badge variant={row.type==="PAYIN_FEE"?"blue":row.type==="AP_RELATION"?"violet":"amber"}>{row.type}</Badge></td><td>{row.imported}</td><td>{row.calculated}</td><td style={{color:row.status==="MISMATCH"?"#b82f3a":undefined}}>{row.diff}</td><td><Badge variant={row.status==="MATCH"?"green":row.status==="REVIEW"?"amber":"red"}>{row.status}</Badge></td><td className="mono muted">{row.batch}</td></tr>)}</tbody></table></div><Pagination total={12}/></Card>
 </>}
